config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations], controllers: {
    sessions: "admin/sessions",
  }

  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
  }

  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about"

    resources :users, only: [:show, :edit, :update]
    get "/diaries/calendar_detail/:year/:month/:day" => "diaries#calendar_detail", as: 'calendar_detail'
    get "/diaries/favorited_diary" => "diaries#favorited_diary", as: 'favorited_diary'
    patch "diaries/favorited_off/:id" => "diaries#favorited_off", as: 'diary_favorited_off'
    resources :diaries, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    get 'homes/top'
    resources :emotions, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  has_many_attached :images, dependent: :destroy
  has_many :image_emotions, dependent: :destroy

  accepts_nested_attributes_for :image_emotions, reject_if: :all_blank, allow_destroy: true
end

app/models/emotion.rb
class Emotion < ApplicationRecord
  has_many :image_emotions, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  belongs_to :diary
end

app/models/image_emotion.rb
class ImageEmotion < ApplicationRecord
  belongs_to :diary
  belongs_to :emotion
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :Images, dependent: :destroy
  has_many :diaries, dependent: :destroy
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/emotions_controller.rb
class Admin::EmotionsController < ApplicationController
  # before_action :authenticate_admin!

  def new
    @emotion = Emotion.new
  end

  def create
    @emotion = Emotion.new(emotion_params)
    @emotion.save
    redirect_to admin_emotions_path
  end

  def index
    @emotions = Emotion.all
  end

  def edit
    @emotion = Emotion.find(params[:id])
  end

  def update
    @emotion = Emotion.find(params[:id])
    @emotion.update(emotion_params)
    redirect_to admin_emotions_path
  end

  def destroy
    @emotion = Emotion.find(params[:id])
    @emotion.destroy
    redirect_to admin_emotions_path
  end

  private

  def emotion_params
    params.require(:emotion).permit(:emotion_name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    admin_homes_top_path
  end

  def after_sign_out_path_for(resource)
    admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_up_path_for
    about_path
  end
end

app/helpers/admin/emotions_helper.rb
module Admin::EmotionsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/emotions/edit.html.erb
<div class="container">
  <h1 class="mb-2">感情編集</h1>
  <%= form_with model: @emotion, url: admin_emotion_path(@emotion.id), method: :patch, local:true do |f| %>
    <div class="diary_box mb-5 mt-5">
      <%= f.text_field :emotion_name, class:"mb-3" %><br>
      <%= f.submit "更新する" ,class:"btn btn-outline-secondary"%>
    </div>
  <% end %>
</div>

app/views/admin/emotions/index.html.erb
<div class="container">
  <h1 class="mb-2">感情一覧</h1>
    <p><i class="fas fa-plus"></i><%= link_to "感情追加" , new_admin_emotion_path, class:"text-secondary" %></p>
      <table class="table">
        <% @emotions.each do |emotion| %>
        <tbody>
          <tr>
            <td><%= emotion.emotion_name %></th>
            <td><%= link_to "編集する", edit_admin_emotion_path(emotion.id), class:"btn btn-outline-secondary" %></td>
            <td><%= link_to "削除する", admin_emotion_path(emotion.id) , method: :delete, class:"btn btn-outline-danger","data-confirm" => "削除しますか？" %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
</div>

app/views/admin/emotions/new.html.erb
<div class="container">
  <h1 class="mb-2">感情新規登録</h1>
    <%= form_with model: @emotion, url: admin_emotions_path, method: :post, local:true do |f| %>
    <div class="diary_box mb-5 mt-5">
      <p>感情名</p>
      <%= f.text_field :emotion_name, class:"mb-3" %><br>
      <%= f.submit "登録",class:"btn btn-outline-secondary" %>
    </div>
    <% end %>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <h1>管理者メニュー</h1>
  <p><i class="fas fa-heart"></i><%= link_to "感情操作", admin_emotions_path, class:"text-secondary" %></p>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmotionDiary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/ab08715929.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
　<% if user_signed_in? || admin_signed_in? %>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="fasse" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
  <% end %>

            <% if user_signed_in? %>
              <div class="ml-4">ようこそ<%= current_user.name %>さん</div>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">

                  <ul class="navbar-nav ml-auto">

                    <li class="nav-item p-3">
                    <i class="fas fa-feather"></i>
                    <%= link_to "今日の記録", new_diary_path, class:"text-secondary" %>
                    </li>

                    <li class="nav-item p-3">
                    <i class="fas fa-calendar-day"></i>
                    <%= link_to "カレンダー", diaries_path, class:"text-secondary" %>
                    </li>

                    <li class="nav-item p-3">
                    <i class="fas fa-star"></i>
                    <%= link_to "お気に入り", favorited_diary_path, class:"text-secondary" %>
                    </li>

                    <li class="nav-item p-3">
                    <i class="fas fa-question-circle"></i>
                    <%= link_to "使い方", about_path, class:"text-secondary" %>
                    </li>

                    <li class="nav-item p-3">
                    <i class="fas fa-user"></i>
                    <%= link_to "マイページ", user_path(current_user.id), class:"text-secondary" %>
                    </li>

                    <li class="nav-item p-3">
                    <i class="fas fa-sign-out-alt"></i>
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"text-secondary" %>
                    </li>

                  </ul>
                </div>
              </div>
            <% elsif admin_signed_in? %>
              <div class="ml-4">管理者用ページにログイン中です</div>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                  <ul class="navbar-nav ml-auto">

                    <li class="nav-item">
                    <i class="fas fa-toolbox"></i>
                    <%= link_to "管理者メニュー画面へ", admin_homes_top_path,class:"text-secondary" %>
                    </li>

                    <li class="nav-item">
                    <i class="fas fa-sign-out-alt"></i>
                    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"text-secondary" %>
                    </li>
                  </ul>
                </div>
              </div>
            <% end %>
      </nav>
    </header>

    <main>
    <%= yield %>
    </main>
  </body>
</html>